sudo: false

language: node_js
node_js:
  - "6.5.0"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - openjdk-7-jdk
    - lib32stdc++6
    - lib32z1
env:
  CXX=g++-4.8

install:
  - npm install -g cordova ionic
  - npm install

before_script:
  - mkdir www

script:
  - cordova prepare